spring:
  config:
    import:
      - optional:file:.env[.properties]
      - security-config.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/career_fit
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always



ai:
  server:
    base-url: http://localhost:8000 # AI 서버 개발자(현준님)에게 받은 실제 주소로 변경해야 합니다.