spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/career_fit
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

jwt:
  secret-key: ${SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d}
  access-token-validity-millis: ${ACCESS_TOKEN_VALIDTY:3600000}
  refresh-token-validity-millis: ${REFRESH_TOKEN_VALIDITY:604800000}
  issuer: ${ISSUER:http://career-fit.com}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  authorize-uri: ${KAKAO_AUTAHORIZE_URI:https://kauth.kakao.com/oauth/authorize}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}
  urls:
    base-auth: https://kauth.kakao.com
    base-api: https://kapi.kakao.com
    token: /oauth/token
    authorize: /oauth/authorize
    user-info: /v2/user/me
    unlink: /v1/user/unlink
