spring:
  config:
    import:
      - security-config.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

ai:
  server:
    base-url: ${AI_SERVER_URL} # AI 서버 개발자(현준님)에게 받은 실제 주소로 변경해야 합니다.

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      region-value: ap-northeast-2