name: Career-fit CD Pipeline - Prod

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/career-fit-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/career-fit-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/career-fit
            echo "${{ secrets.ENV_PROD }}" > .env
            export DOCKER_IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/career-fit-app"
            export IMAGE_TAG="${{ github.sha }}"
            docker pull $DOCKER_IMAGE_NAME:$IMAGE_TAG
            docker-compose down
            docker-compose up -d
            docker image prune -f